PVH_news:
  ticker: PVH
  url: https://www.pvh.com/news?facets=year%3D2025%7C2024%7C2023%7C2022%7C2021%7C2020%7C2019%26
  output: data/PVH_news.json
  output_json: JSONS/PVH_news.json
  base_address: https://www.pvh.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: li.list__item                   # Each event is in a <li> with class "list__item"
  pagination:
    type: button
    next_button: button:has(i.mdi-chevron-right):not(.v-pagination__navigation--disabled)

PVH_press:
  ticker: PVH
  url: https://www.pvh.com/news?facets=content_type%3DPress%20Releases
  output: data/PVH_press2.json
  output_json: JSONS/PVH_press2.json
  base_address: https://www.pvh.com/
  category: 'news'
  periodic: false
  geography: "US"
  llm: true
  selectors:
    event_block: li.list__item
    parent_event_block: div.content__main.col-md-8.offset-md-0.order-md-1.col-12.order-2                   # Each event is in a <li> with class "list__item"
  pagination:
    type: button
    next_button: button:has(i.mdi-chevron-right):not(.v-pagination__navigation--disabled)

PVH_reports:
  ticker: PVH
  scraper: FlatListScraper
  url: https://www.pvh.com/investor-relations/reports
  output: data/PVH_reports.json
  selectors:
    event_block: div.col-md-6
  pagination:
    type: null
    next_button: null

PVH_resources:
  ticker: PVH
  scraper: FlatListScraper
  url: https://www.pvh.com/responsibility/resources
  output: data/PVH_resources.json
  selectors:
    event_block: .layout__wrap.story-well.ready, .container.layout
  pagination:
    type: null
    next_button: null

PVH_events:       # COMPLETED
  ticker: PVH
  scraper: null
  url: https://www.pvh.com/news?facets=year%3D2025%7C2024%7C2023%7C2022%7C2021%7C2020%7C2019%7C2018%7C2017%7C2016%7C2015%7C2014%7C2013%7C2012%7C2011%7C2010%7C2009%26
  output: data/PVH_events.json
  output_json: JSONS/PVH_events.json
  base_address: https://www.pvh.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: li.list__item
  pagination:
    type: button
    next_button: button:has(i.mdi-chevron-right):not(.v-pagination__navigation--disabled)

CORZ_financial-information:
  ticker: CORZ
  scraper: null
  url: https://investors.corescientific.com/financial-information/financial-results
  output: data/CORZ_financial-information.json
  output_json: JSONS/CORZ_financial-information.json
  base_address: https://investors.corescientific.com/
  periodic: true
  geography: "US"
  selectors:
    event_block: xpath=//div[@class=" row"]
  pagination:
    type: null
    next_button: null
  defaults:
    event_type: webcast
  cutoff:
    years_back: 5

CORZ_presentations:
  ticker: CORZ
  scraper: null
  url: https://investors.corescientific.com/news-events/presentations
  output: data/CORZ_presentations.json
  output_json: JSONS/CORZ_presentations.json
  base_address: https://investors.corescientific.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: article.media
  pagination:
    type: next_page_url
    next_button: page-link
  defaults:
    event_type: webcast
  cutoff:
    years_back: 5 

CORZ_press:         # Pagination not being handled correctly
  ticker: CORZ
  scraper: null
  url: https://investors.corescientific.com/news-events/press-releases
  output: data/CORZ_press.json
  output_json: JSONS/CORZ_press.json
  base_address: https://investors.corescientific.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: article.media
  pagination:
    type: next_page_url
    next_button: a.page-link
  defaults:
    event_type: webcast
  cutoff:
    years_back: 5 

CRDA_esg:     # Downloads unsuccessful 403
  ticker: CRDA
  url: https://www.croda.com/en-gb/investors/environmental-social-and-governance-esg
  output: data/CRDA_esg.json
  output_json: JSONS/CRDA_esg.json
  base_address: https://www.croda.com/en-gb/
  periodic: false
  geography: "US"
  selectors:
    event_block: div.card-body
  pagination:
    type: null
    next_button: null
  defaults:
    event_type: webcast
  cutoff:
    years_back: 5

CRDA_presentations:     # Too many irrelevant event blocks scrapped
  ticker: CRDA
  scraper: null
  url: https://www.croda.com/en-gb/investors/results-presentations-and-reports
  output: data/CRDA_presentations.json
  output_json: JSONS/CRDA_presentations.json
  base_address: https://www.croda.com/en-gb/
  periodic: false
  geography: "US"
  selectors:
    event_block: table.c-responsive-table tbody tr
  pagination:
    type: null
    next_button: null

CBP_events:         # Pagination not being handled correctly
  ticker: CBP
  url: https://investor.thecampbellscompany.com/events-presentations
  output: data/CBP_events.json
  output_json: JSONS/CBP_events.json
  base_address: https://investor.thecampbellscompany.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: article.node--nir-event--nir-widget-list
  pagination:
    type: next_page_url
    next_button: li.pager__item--next a
  defaults:
    event_type: webcast
  cutoff:
    years_back: 5

CBP_news:
  ticker: CBP
  url: https://investor.thecampbellscompany.com/news/financial-news
  output: data/CBP_news.json
  output_json: JSONS/CBP_news.json
  base_address: https://investor.thecampbellscompany.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: article.node--nir-news--nir-widget-list
  pagination:
    type: load_more
    next_button: a.button.use-ajax[rel='next']

#DSFIR
DSFIR_news:       #COMPLETED
  ticker: DSFIR
  url: https://investors.dsm-firmenich.com/en/investors/historical-information/corporate-governance/agm.html
  output: data/DSFIR_news.json
  output_json: JSONS/DSFIR_news.json
  base_address: https://investors.dsm-firmenich.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: li.cmp-list__item.common-list__item:is(:visible)
  pagination:
    type: button
    next_button: div.cmp-button a.cmp-list__pagination--next

DSFIR_press:    # working
  ticker: DSFIR
  scraper: null
  url: https://investors.dsm-firmenich.com/en/investors/historical-information/results-presentations.html
  output: data/DSFIR_press.json
  output_json: JSONS/DSFIR_press.json
  base_address: https://investors.dsm-firmenich.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: .cmp-title, .cmp-text, .cmp-image
  pagination:
    type: year_tabs
    next_button: "li.cmp-tabs__tab"

GIVN_news:          # load more button not COMPLETED
  ticker: GIVN
  url: https://www.givaudan.com/media/media-releases?keyword=&im_givaudan_publication_year=All&tm_vid_1_names=All&tm_vid_1_names_adhoc=All
  output: data/GIVN_news.json
  output_json: JSONS/GIVN_news.json
  base_address: https://www.givaudan.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: div.views-row.show
  pagination:
    type: load_more
    next_button: div.load-more-news button

IFF_presentations:    # COMPLETED
  ticker: IFF
  url: https://ir.iff.com/events-presentations
  output: data/IFF_presentations.json
  output_json: JSONS/IFF_presentations.json
  base_address: https://ir.iff.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: article.node--nir-event--nir-widget-list
  pagination:
    type: null
    next_button: null

IFF_press:      # pagination not being handled correctly
  ticker: IFF
  scraper: null
  url: https://ir.iff.com/press-releases?6975432388c93f18be7b4d8222cbf202d2f07feef130201ed2393ef8b833b15d_year%5Bvalue%5D=_none&op=Filter&6975432388c93f18be7b4d8222cbf202d2f07feef130201ed2393ef8b833b15d_widget_id=6975432388c93f18be7b4d8222cbf202d2f07feef130201ed2393ef8b833b15d&form_build_id=form-bkOO9-pFrxeEqyo53ECPHSIhD5BNRO5mz4vNrzsfUAg&form_id=widget_form_base
  output: data/IFF_press.json
  output_json: JSONS/IFF_press.json
  base_address: https://ir.iff.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: .nir-widget--list article
  pagination:
    type: next_page_url
    next_button: a

KO_company-updates:     # scrapped 4 blocks instead of 6
  ticker: KO
  scraper: null
  url: https://investors.coca-colacompany.com/
  output: data/KO_company-updates.json
  output_json: JSONS/KO_company-updates.json
  base_address: https://investors.coca-colacompany.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: .ir-cta-event-with-documents
  pagination:
    type: null
    next_button: null

KO_poclicies-practices-reports:     # all events not scrapped
  ticker: KO
  url: https://www.coca-colacompany.com/policies-and-practices/
  output: data/KO_poclicies-practices-reports.json
  output_json: JSONS/KO_poclicies-practices-reports.json
  base_address: https://www.coca-colacompany.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: div.cmp-accordion__item div div div div div div ul li
  pagination:
    type: null
    next_button: null

KO_press:     # COMPLETED
  ticker: KO
  url: https://investors.coca-colacompany.com/news-events/press-releases
  output: data/KO_press.json
  output_json: JSONS/KO_press.json
  base_address: https://investors.coca-colacompany.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: article.media
  pagination:
    type: button
    next_button: div.control.next a

RL_newsroom:      # COMPLETED
  ticker: RL
  url: https://corporate.ralphlauren.com/newsroom
  output: data/RL_newsroom.json
  output_json: JSONS/RL_newsroom.json
  base_address: https://corporate.ralphlauren.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: .newsroom-content .corp-news
  pagination:
    type: load_more
    next_button: div.corp-secondary-button a

SY1_events:     # COMPLETED
  ticker: SY1
  scraper: null
  url: https://www.symrise.com/investors/financial-calendar-and-presentations/
  output: data/SY1_events.json
  output_json: JSONS/SY1_events.json
  base_address: https://www.symrise.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: div.t-row
  pagination:
    type: null
    next_button: null

SY1_news:         # pagination not handled correctly
  ticker: SY1
  url: https://www.symrise.com/newsroom/press-releases/
  output: data/SY1_news.json
  output_json: JSONS/SY1_news.json
  base_address: https://www.symrise.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: div.t-table
  pagination:
    type: year_tabs
    next_button: .tab-titles:not(.panel-inverted) a

WDAY_events: #COMPLETED
  ticker: WDAY
  scraper: null
  url: https://investor.workday.com/events#past:2025:3
  output: data/WDAY_events.json
  output_json: JSONS/WDAY_events.json
  base_address: https://investor.workday.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: div.wd_events_month
  pagination:
    type: load_more
    next_button: button.wd_events_more

WDAY_press:
  ticker: WDAY
  url: https://investor.workday.com/press-releases
  output: data/WDAY_press.json
  output_json: JSONS/WDAY_press.json
  base_address: https://investor.workday.com/
  periodic: false
  geography: "US"
  selectors:
    event_block: .wd_item
  pagination:
    type: button
    next_button: li.wd_page_link.wd_page_next a

WMT_quarterly:
  ticker: WMT
  scraper: null
  url: https://stock.walmart.com/financial-information/vizio-historical-financials
  output: data/WMT_quarterly.json
  output_json: JSONS/WMT_quarterly.json
  base_address: https://stock.walmart.com/
  periodic: true
  geography: "US"
  selectors:
    event_block: div.box quarterly-results
  pagination:
    type: button
    next_button: button:has(i.mdi-chevron-right):not(.v-pagination__navigation--disabled)
