PVH_news:
  ticker: PVH
  scraper: FlatListScraper
  url: https://www.pvh.com/news
  output: output/PVH_news.json
  selectors:
    event_block: div.row.content__container
    event_name: a
    event_date: p.list__date
    file_links: a
  pagination:
    type: button
    next_button: button:has(i.mdi-chevron-right):not(.v-pagination__navigation--disabled)
  defaults:
    event_type: press_release
  cutoff:
    years_back: 5
